### ISSUE TITLE
Add support to import existing account via private key

### ISSUE THREAD

**Issue by codeWhizperer** [xJonathanLEI/starkli#107]
Adding the flexibility of importing existing Argent or Braavos wallets for declaration, deployment, or invocation.

**Comment by xJonathanLEI** [comment]
Hi @codeWhizperer this feature has always existed. Have you checked out [account fetching](https://book.starkli.rs/accounts#account-fetching)? It should be exactly what you're looking for.

Closing this optimistically. Feel free to re-open if it's not helping.

**Comment by mateocovacho** [comment]
@xJonathanLEI 

Hi I am having trouble importing an existing argent-x account to starkli

RPC working  ✅
argent-x account fetched ✅
Account contract type identified as: Argent X
Description: Argent X official account (as of 5.13.1)

keystore generated ✅
fails to invoke contract !  ❌
starkli invoke 0x055af11f4ab3dfbdf701960d5d4cf19f722a8a2dd42a38aa6acdec242e320391 get_entry_code --account ./main  --fee-token STRK
Enter keystore password:
Error: TransactionExecutionError (tx index 0): failed txn 2315825742166176926625714465040038439580451682509463144539433166038606729938 reason: Transaction validation has failed:
0: Error in the called contract (contract address: 0x055af11f4ab3dfbdf701960d5d4cf19f722a8a2dd42a38aa6acdec242e320391, class hash: 0x029927c8af6bccf3f6fda035981e765a7bdbf18a2dc0d
630494f8758aa908e2b, selector: 0x0162da33a4585851fe8d3af3c2a9c60b557814e221e0d4f30ff0b2189d9c7775):
Execution failed. Failure reason: 0x617267656e742f696e76616c69642d6f776e65722d736967 ('argent/invalid-owner-sig').
 Execution failed. Failure reason: 0x617267656e742f696e76616c69642d6f776e65722d736967 ('argent/invalid-owner-sig').


i seem to not have provided verification that I own the existing account. How do i do so ?
