### ISSUE TITLE
Trimmed error message

### ISSUE THREAD

**Issue by milancermak** [xJonathanLEI/starkli#13]
Ran into an error when I was deploying a contract. However the error message I got back from `starkli` seems to be trimmed:

```
Error: JSON-RPC error: code=-32603, message="Internal error: StarknetErrorCode.TRANSACTION_FAILED: Error at pc=0:12:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:161)
Unknown location (pc=0:147)

Error in the called contract (0x765c1816..."
```

That was all that got printed out, in read, to the terminal. Can you please make it print the whole error? Or is it trimmed somewhere else?

**Comment by xJonathanLEI** [comment]
Pretty sure this is trimmed by the JSON-RPC node itself instead of `starkli` bit lemme test.

**Comment by xJonathanLEI** [comment]
Tested with an invoke tx (deployments are just `INVOKE` anyways) and got something similar. Printed the original traffic and found this:

```log
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Internal error: StarknetErrorCode.TRANSACTION_FAILED: Error at pc=0:25:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:731)\nUnknown location (pc=0:677)\nUnknown location (pc=0:291)\nUnknown locat..."},"id":1}
```

So apparently the JSON-RPC node itself trimmed the error in the first place. `starkli` never trims error messages.

There's nothing `starkli` can do to fix this. Closing since it's not actionable.

**Comment by milancermak** [comment]
Thanks for checking! Do you know where can I open a bug to get this fixed? :) I remember there being a JSON-RPC specs repo, but can't find it now.

**Comment by xJonathanLEI** [comment]
The specs doesn't govern whether error messages are trimmed or not I believe. You would need to file this to the node implementations themselves (i.e. `pathfinder`).

**Comment by xJonathanLEI** [comment]
Found it:

https://github.com/eqlabs/pathfinder/blob/dce6d72fc274bc45a7c59696be9dec91d05b7a58/py/src/pathfinder_worker/call.py#L396-L402

**Comment by Mirko-von-Leipzig** [comment]
Yeah we started truncating them after we found extreme cases where the messages were GB in size..

200 chars is rather way too short though, will extend that.
