### ISSUE TITLE
Issue with starknet-devnet interaction resulting in response decoding error

### ISSUE THREAD

**Issue by omarespejel** [xJonathanLEI/starkli#16]
Hey! Amazing tool! It is currently the recommended way to interact with Starknet in the [Starknet Book](https://book.starknet.io/chapter_1/first_contract.html).

I'm running into a bit of trouble with the devnet, though. I want to add to the Book some examples using the devnet and starkli. I've set up the Signer and Account Descriptor for an Account on starknet-devnet. But I get an error when I try to declare with the devnet. Here's the command I'm using:

```
❯ starkli declare target/dev/starknetbook_chapter_2_Vote.sierra --rpc=http://127.0.0.1:5000/ --compiler-version=2.0.1

Error: error decoding response body: expected value at line 1 column 1
```

No such issue when I'm on the testnet. The same error pops up when I'm making other calls with the devnet. For example:

```
❯ starkli class-hash-at 0x7e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a --rpc=http://127.0.0.1:5000

Error: error decoding response body: expected value at line 1 column 1
```

Any help would be great! Thanks for your time.

**Comment by xJonathanLEI** [comment]
Hey @omarespejel thanks for reporting the issue.

I'm not exactly sure whether `starknet-devnet` supports JSON-RPC though? IIRC `starknet-devnet` only exposes the sequencer gateway API?

If that's the case:

Starkli _does_ support the sequencer gateway API, but it does so in a way that only live networks are supported. You can use it with the `--network` option.

It's technically trivial for Starkli to also accept custom sequencer gateway URLs, and therefore support this use case. However, Starkli deliberately does not ship with this feature to discourage the use of sequencer gateway, which is deprecated.

Could you please help me understand the importance of this use case? Maybe it's worth supporting after all? Or can you switch to a devnet implementation that uses JSON-RPC (e.g. `kanata`) instead?

**Comment by xJonathanLEI** [comment]
Reference: https://book.starkli.rs/providers#sequencer-gateway

**Comment by omarespejel** [comment]
Hi @xJonathanLEI, thank you for your kind explanation!

I agree with what you mentioned. I am then using `katana` as the development network for the Starknet Book.

It is working perfectly with `starkli`!
