### ISSUE TITLE
skarkli declare error

### ISSUE THREAD

**Issue by cymqqqq** [xJonathanLEI/starkli#19]
Hi there, I used the command "starkli declare" to declare my sierra code, but it prints:
<img width="737" alt="image" src="https://github.com/xJonathanLEI/starkli/assets/8555534/cd9ad0f4-bc56-4042-901f-105dc0b087ec">
I don't know why, my scarb version=0.5.2

**Comment by glihm** [comment]
Hello @cymqqqq,

at the moment, only the cairo version available with scarb `v0.5.1` can be declared/deployed on chain. You can find the help note in [this section of the book](https://book.starkli.rs/tutorials/starkli-101#compile-your-cairo-contract).

If you need to install a specific version of scarb, please [check their tool](https://docs.swmansion.com/scarb) `asdf` to easily switch between versions.

Please let us know that it's all ok with the correct version.

**Comment by cymqqqq** [comment]
Hi @glihm , I install scarb 0.5.1 and rebuild it, and now it can be declared by scarkli and generate a class hash.
But then I failed in the next step: starkli deploy class_hash, it prints:
![image](https://github.com/xJonathanLEI/starkli/assets/8555534/2a005810-d619-4146-b9a7-63902df52fe8)

**Comment by cymqqqq** [comment]
Hi @glihm , it works, thx 👍
