### ISSUE TITLE
Installation issue for macOS with oh-my-zsh

### ISSUE THREAD

**Issue by edisontim** [xJonathanLEI/starkli#20]
After running: 
```
curl https://get.starkli.sh | sh
```
and launching a new shell I get
```
compinit:141: parse error: condition expected: $1
compinit:571: compinit: function definition file not found
/Users/timothyedison/.starkli/env:16: compinit: function definition file not found
```
Issue is coming from this line added in .profile: 
```
. "/Users/timothyedison/.starkli/env"
```
When commenting it (it's already present in .zshrc in my case) everything works fine.

**Comment by xJonathanLEI** [comment]
Sorry for not attending this issue for so long. Has the issue been resolved?

**Comment by edisontim** [comment]
No it's fixed :)
