### ISSUE TITLE
can't fetch oz account

### ISSUE THREAD

**Issue by wenzhenxiang** [xJonathanLEI/starkli#26]
starkli version 0.1.10 (90ba98c) 
I use the cairo2.1.0 compiler，depolyed a oz account
can't fetch oz account，argent is OK

starkli account fetch 0x041ffa911a144d39e2c7bbb2c6c7eaf1594f6b2669e1cbcc02f9d769aaf5e148
NOTE: --output is not supplied and the account config won't be persisted.
WARNING: no valid provider option found. Falling back to using the sequencer gateway for the goerli-1 network. Doing this is discouraged. See https://book.starkli.rs/providers for more details.
0x048ee94b4dd54b5d2287fc9dd33834bd30ecd3bed6e92d7e8097b4a55dcaccf0 is not a known account class hash. If you believe this is a bug, submit a PR to:
    https://github.com/xJonathanLEI/starkli
Error: unknown class hash: 0x048ee94b4dd54b5d2287fc9dd33834bd30ecd3bed6e92d7e8097b4a55dcaccf0

**Comment by wenzhenxiang** [comment]
After reading the [account.re code](https://github.com/xJonathanLEI/starkli/blob/master/src/account.rs), I think know the reason, the existing one is based on  : "OpenZeppelin account contract v0.6.1 compiled with cairo-lang v0.11.0.2" ，I'm use new version, so can't fetch

**Comment by xJonathanLEI** [comment]
Yes Starkli uses a predefined known class hash table to be able to recognize account contract variants. I will take a look at this tomorrow and add the relevant hash. Thanks for flagging this.

**Comment by xJonathanLEI** [comment]
I checked your class hash: `0x048ee94b4dd54b5d2287fc9dd33834bd30ecd3bed6e92d7e8097b4a55dcaccf0`, which is OZ's unreleased Cairo 1 implementation. Unfortunately there's currently no plan to support unreleased versions of account contracts. You'll need to manually modify a normal OZ account file to be able to use it with Starkli.

**Comment by wenzhenxiang** [comment]
ok
