### ISSUE TITLE
Issue installing on MacOSX

### ISSUE THREAD

**Issue by coburn24** [xJonathanLEI/starkli#29]
running 
`curl https://get.starkli.sh | sh`
then whether i open a new window or run 
`. /Users/Matt/.starkli/env`
and run `starkliup`
I get the following error 
`Couldn't download release file for tag '' from GitHub [404].`
<img width="610" alt="Screen Shot 2023-08-28 at 11 00 19 AM" src="https://github.com/xJonathanLEI/starkli/assets/29192260/4053a0b4-b481-488d-a024-1182a515a84e">

**Comment by xJonathanLEI** [comment]
The line _Latest version found:_ is where it went wrong. Looks like the script somehow wasn't able to determine the latest release version.

Are you still experiencing the issue?

**Comment by xJonathanLEI** [comment]
Closing since no further information is provided. Feel free to re-open if the issue persists.
