### ISSUE TITLE
short string exceed 31 character limit

### ISSUE THREAD

**Issue by chirag-bgh** [xJonathanLEI/starkli#3]
$ starkli to-cairo-string 0x0740c2dd633f2611BF0dB5220317FF6b0fBa399989a3f94b386C7aD26C54D47d
Error: short string exceeds maximum length of 31 characters

**Comment by xJonathanLEI** [comment]
`starkli parse-cairo-string 0x0740c2dd633f2611BF0dB5220317FF6b0fBa399989a3f94b386C7aD26C54D47d`

**Comment by xJonathanLEI** [comment]
I was assuming you're trying to decode instead of encode. If you're really trying to encode, then it's not a Cairo short string. Cairo short strings are 31 characters at max.

Maybe you're looking for a different string encoding scheme?

**Comment by xJonathanLEI** [comment]
Closing this optimistically as it doesn't seem to be actionable. This command is for Cairo short strings, which is officially documented here:

https://www.cairo-lang.org/docs/how_cairo_works/consts.html#short-string-literals
