### ISSUE TITLE
Is it possible to allow override of cairo compiler? 

### ISSUE THREAD

**Issue by arijoon** [xJonathanLEI/starkli#30]
Scarb allows the override of the cairo compiler: https://github.com/software-mansion/scarb/blob/529865094ea02ea67e77e07f1f0e8161e287f809/scarb/build.rs#L36 by simply setting the archive path of CARIO_ARCHIVE

This makes it very easy especially when building with nix to simply set the compiler/binaries version and upgrade without requiring a scarb upgrade. Is it possible to do something similar on this project to avoid requiring a starkli code change in order to bump the cairo compiler? (for example cairo compiler is on 2.2.0 now but starkli is on 2.1.0)

I'm assuming non breaking changes at the risk of the user

**Comment by xJonathanLEI** [comment]
Implemented in https://github.com/xJonathanLEI/starkli/commit/8d2fe49339fafe73c7071735be9c0d469dc96041.

Just point to your `starknet-sierra-compile` binary with `--compiler-path`.
