### ISSUE TITLE
Feature Request: support for the `starkli storage` command write variable name

### ISSUE THREAD

**Issue by wenzhenxiang** [xJonathanLEI/starkli#32]
request support for the `starkli storage` command, which would allow user to directly write a storage variable name and retrieve its value, doesn't require the user to calculate storage key.

thank you for your great work on starkli!

**Comment by glihm** [comment]
@wenzhenxiang thanks for the issue and sorry for the delay.

To `set` a storage value, you must send a transaction that calls a contract, which in turns can modify the storage.

Also, the RPC specification only allows `getStorageAt`, which is used to read the storage at the given contract address. This is why `starkli storage` **gets** the value.

If you need to do so for testing purposes, please check the progess of [starknet-foundry](https://github.com/foundry-rs/starknet-foundry) where a `cheatcode` for setting storage manually will be available soon.

@xJonathanLEI can be closed, not in the scope of starkli.

**Comment by xJonathanLEI** [comment]
I think he means `starkli storage ERC20_name`.

**Comment by glihm** [comment]
oh, got you, sorry @wenzhenxiang and thank you @xJonathanLEI. Title was misleading me a bit then. x)

**Comment by xJonathanLEI** [comment]
Implemented in https://github.com/xJonathanLEI/starkli/commit/d0e96eb9be1cf1107cf3236a467d40ac05e30d80. Will be shipped in the next release.

You can now do:

```console
starkli storage eth ERC20_name
```

or explicitly:

```console
starkli storage addr:eth storage:ERC20_name
```
