### ISSUE TITLE
starkli account fetch command unexpected argument error

### ISSUE THREAD

**Issue by blhq111** [xJonathanLEI/starkli#34]
I was following the Starknet developer documentation and encountered an issue while trying to use the starkli account fetch command. The documentation suggests the following command:
starkli account fetch 0x0--------C--F2 ~/starkli-wallets/deployer/account.json
However, when I tried to execute this command, I received the following error:

error: unexpected argument '/Users/baiyuguang/starkli-wallets/deployer/account.json' found
Usage: starkli account fetch [OPTIONS] <ADDRESS>

when i use this command:
<img width="1497" alt="image" src="https://github.com/xJonathanLEI/starkli/assets/32098020/58b6d5d0-fb62-406d-b680-4b94ab9ee807">

**Comment by xJonathanLEI** [comment]
This command:

```console
starkli account fetch 0x0--------C--F2 ~/starkli-wallets/deployer/account.json
```

is wrong. The output path must be given through the `--output` option. So it must be:

```console
starkli account fetch 0x0--------C--F2 --output ~/starkli-wallets/deployer/account.json
```

instead.

Note that in your screenshot, when you're using the command this way, you're getting a `ContractNotFound` error, not `unexpected argument`. That means the address you're putting in does not exist in the `goerli-1` network.

If you're trying to use `mainnet`, you need to either set a JSON-RPC provider pointing to `mainnet`, or add the `--network mainnet` option. See [the book](https://book.starkli.rs/providers) for details.
