### ISSUE TITLE
`Error: code=-32603, message="Internal error: Execution failed. Failure reason: "Input too long for arguments"."`

### ISSUE THREAD

**Issue by maxgiraldo** [xJonathanLEI/starkli#36]
Following Starknet book at https://book.starknet.io/chapter_1/first_contract.html#invoking_a_write_function, I got an error running the following command:

```
starkli invoke \
    <CONTRACT_ADDRESS> \
    transfer_ownership \
    <NEW_OWNER_ADDRESS> \
    --network=goerli-1
```

`Error: code=-32603, message="Internal error: Execution failed. Failure reason: "Input too long for arguments"."`

**Comment by xJonathanLEI** [comment]
What account contract are you using? Argent X? Has it been upgraded to Cairo 1?

**Comment by maxgiraldo** [comment]
https://testnet.starkscan.co/contract/0x02d40bdc7b27c71491fb3afe4c24cef03c99f8286e64a25e4533f5a4a87f7f18

I now get the error: `Error: Mac Mismatch`

**Comment by xJonathanLEI** [comment]
This error is exactly caused by upgrading to Cairo 1. I will make a new release tomorrow with the fix.

**Comment by xJonathanLEI** [comment]
Argent Cairo 1 account contract is now supported (in [v0.1.14](https://github.com/xJonathanLEI/starkli/releases/tag/v0.1.14)). Upgrade your Starkli installation with `starkliup` and re-fetch the account file.
