### ISSUE TITLE
Need help, program don't works

### ISSUE THREAD

**Issue by CharGitWork** [xJonathanLEI/starkli#37]
Hello,
I can't get your program to work and the documentation is incomplete.
I've already opened an issue but it didn't help.

Can you just list the steps required (commands) to deploy a smart contract, on a katana node for example?

**Comment by xJonathanLEI** [comment]
What does it even mean that it doesn't work? Don't expect proper answers without proper questions.

https://github.com/xJonathanLEI/starkli-ci-test/actions

**Comment by CharGitWork** [comment]
![Capture d'écran 2023-09-19 091149](https://github.com/xJonathanLEI/starkli/assets/133235269/97eb27d2-1af3-4d07-ba00-86efcaa12059)
![Capture d'écran 2023-09-19 091243](https://github.com/xJonathanLEI/starkli/assets/133235269/d3be0e43-9448-4562-943d-2f9231edb453)

**Comment by CharGitWork** [comment]
I'm trying to deploy the example contract of cairo book: https://book.cairo-lang.org/ch99-01-04-01-voting-contract.html

**Comment by CharGitWork** [comment]
Can you explain me the error please?
