### ISSUE TITLE
Add support for `non-known` account class hash 

### ISSUE THREAD

**Issue by glihm** [xJonathanLEI/starkli#38]
As we've seen recently, lot's of people without coding background are struggling using custom account with starkli.

Could we think about a way that Starkli is not checking the account class hash, even if we have to display an error message?

Because in the first idea it was that any people using custom account contract will have the knowledge to edit files manually. But with katana or other devnet we've seen that new developers / users are facing this issue and don't always have the knowledge to create the files.

WDYT @xJonathanLEI?

**Comment by xJonathanLEI** [comment]
`katana` and devnet accounts can be fetched right?

**Comment by glihm** [comment]
Thank you for the feedback @xJonathanLEI, effectively with latest version it's possible to fetch. :+1:
