### ISSUE TITLE
STARKNET_KEYSTORE not shown in help

### ISSUE THREAD

**Issue by glihm** [xJonathanLEI/starkli#4]
As mentioned in the code [here](https://github.com/xJonathanLEI/starkli/blob/def7aa58ddea1139af0d56fa34a1145af6e5eaf3/src/signer.rs#L72) we don't want the conflict clap would introduce.

In the meantime, having a hand-written `[env: STARKNET_KEYSTORE=]` could be useful for the users that just downloaded Starkli and can have all environment variables from detailed help.

**Comment by xJonathanLEI** [comment]
Resolved by https://github.com/xJonathanLEI/starkli/commit/ddfb5aaa3a0642cf7e2df783104fcf7e9cd2d9a2.
