### ISSUE TITLE
Unable to Deploy Extended ERC20 Contract using starkli v0.1.15

### ISSUE THREAD

**Issue by henryf10h** [xJonathanLEI/starkli#40]
Hello,

I've been encountering a persistent issue when trying to deploy a contract on StarkNet using starkli. Despite multiple attempts and variations in the command structure, I keep receiving the same validation failure error.

Environment:

Starkli Version: 0.1.15
StarkNet Version: v2.2.0
Contract: Extension of the ERC20 standard from OpenZeppelin v0.7.0-rc.0

1.
`starkli deploy --account ~/.starkli-wallets/deployer/account.json --keystore ~/.starkli-wallets/deployer/keystore.json --watch 0x0751012e95eb15318a7036d935c552bf19c526a429c90dc7d8aa611f0e530cc4 u256:100 0x052E6AD8187767eF41F2F3bc225D33d31B37DD9BBEE7B628F4b6b16b90D293EC
`
2.
`starkli deploy --account ~/.starkli-wallets/deployer/account.json --keystore ~/.starkli-wallets/deployer/keystore.json --watch 0x0751012e95eb15318a7036d935c552bf19c526a429c90dc7d8aa611f0e530cc4 u256:100 addr:0x052E6AD8187767eF41F2F3bc225D33d31B37DD9BBEE7B628F4b6b16b90D293EC
`
Expected Behavior:
The contract, which is an extension of the new ERC20 from OpenZeppelin v0.7.0-rc.0, should deploy successfully.

Actual Behavior:
for the first command I received the following error:
`Error: code=ValidationFailure, message="Execution was reverted; failure reason: [0x496e70757420746f6f206c6f6e6720666f7220617267756d656e7473]."
`
(Note: The error message decodes to "Input too long for arguments")

for the second command I get:
Error: address book entry not found for "0x052E6AD8187767eF41F2F3bc225D33d31B37DD9BBEE7B628F4b6b16b90D293EC"

It would be great if you could help identify the root cause of this issue or guide me on any corrective steps to take.

Thank you for your assistance!

**Comment by henryf10h** [comment]
btw, the contract I'm deploying is directly from OpenZeppelin's latest release (v0.7.0-rc.0) - it's their example of extending an ERC20 token for Cairo.

![image](https://github.com/xJonathanLEI/starkli/assets/55424527/18ee94b2-867e-40c8-8e64-9583b8a406d9)

**Comment by xJonathanLEI** [comment]
I believe the issue is with your account contract. Starkli seems to believe your account contract is Cairo 0 while it's actually Cairo 1. What account contract are you using? Is it Argent X? Did you upgrade to Cairo 1? If so, did you re-fetch the account file?

**Comment by henryf10h** [comment]
> I believe the issue is with your account contract. Starkli seems to believe your account contract is Cairo 0 while it's actually Cairo 1. What account contract are you using? Is it Argent X? Did you upgrade to Cairo 1? If so, did you re-fetch the account file?

No, I did not re-fetch the account file. I already did it and I could deploy the contracts. 

Thank you @xJonathanLEI
