### ISSUE TITLE
Help: Issue with `starkli account deploy` - `JsonRpcResponse` Enum Error

### ISSUE THREAD

**Issue by CyndieKamau** [xJonathanLEI/starkli#44]
Hi @xJonathanLEI!! My name is Cyndie.  

I have been contributing to `Account Abstraction` chapters in the starknetbook, using David's tutorials as guidance. 

I have come across an issue that I've been unable to resolve several times now:

## Issue 

When attempting to deploy an account contract with Starkli after successful declaration, using the command below:  

```bash
starkli account deploy ~/.starkli-wallets/custom/account.json
```

I have been getting this Error output consistently:

```bash
Error: data did not match any variant of untagged enum JsonRpcResponse
```

Here's my detailed flow and corresponding output:

```bash
hp@Cyndie:~/Desktop/account_abstraction__starknet/aa$ starkli account deploy ~/.starkli-wallets/custom/account.json
Enter keystore password: 
The estimated account deployment fee is 0.000004330000051960 ETH. However, to avoid failure, fund at least:
    0.000006495000077940 ETH
to the following address:
    0x0062f981ae9d6babd3f6176fbb7fc9e6f7b424e48fcd9b77781ba0076193ec2e
Press [ENTER] once you've funded the address.
Account deployment transaction: 0x058534bd8361061792a8fc9d4c0040e876966abb19991560f875243ac9b7c839
Waiting for transaction 0x058534bd8361061792a8fc9d4c0040e876966abb19991560f875243ac9b7c839 to confirm. If this process is interrupted, you will need to run `starkli account fetch` to update the account file.
Transaction not confirmed yet...
Transaction not confirmed yet...
Error: data did not match any variant of untagged enum JsonRpcResponse
```

## Context and Documentation

For comprehensive context, I have documented my entire setup and deployment process [here](https://github.com/CyndieKamau/account_abstraction__starknet/blob/main/aa/UPDATE_README.md).

## Environment details

- Starkli: `0.1.19 (3fd85cf)`
- Scarb: `scarb 2.3.1 (0c8def3aa 2023-10-31)`
- Cairo: `cairo: 2.3.1 (https://crates.io/crates/cairo-lang-compiler/2.3.1)`
- Sierra: `sierra: 1.3.0`
- RPC Source: Alchemy `https://starknet-goerli.g.alchemy.com/v2/4VUpCv...`

## Attempted solutions

When I tried to check the source code to pin down where the enum `JsonRpcResponse` is I couldn't find it, so I have reached out for help.

Thank you for your time!

**Comment by milancermak** [comment]
Had pretty much the same issue. After switching the RPC from Alchemy to Infura, it went away.

**Comment by xJonathanLEI** [comment]
Can you try running the command again with `--log-traffic`?

**Comment by xJonathanLEI** [comment]
I'm assuming this is the same situation as [this one](https://gist.github.com/milancermak/907cb8999fbc36653528e22662087cfc) provided by @milancermak. If that's the case, then it's because the receipt response from your JSON-RPC endpoint does not include the field `execution_result` as required by spec v0.4.0.

It looks like this endpoint you're using is serving JSON-RPC spec v0.3.0, which does not have this field on receipts. The current version of Starkli only supports v0.4.0.

If you _have to_ use spec v0.3.0, you will need to downgrade Starkli to a previous version that uses this old spec version, as Starkli does not currently support using multiple spec versions side by side (actually, anything before spec v0.4.0 doesn't even offer an option to query the spec version, making it hard to support anyways).

Closing this as not in scope.

**Comment by CyndieKamau** [comment]
Hey @milancermak Yes with Infura it works! Thank you.

```bash
hp@Cyndie:~/Desktop/account_abstraction__starknet/aa$ starkli account deploy ~/.starkli-wallets/custom/account.json
Enter keystore password: 
The estimated account deployment fee is 0.000004330000038970 ETH. However, to avoid failure, fund at least:
    0.000006495000058455 ETH
to the following address:
    0x074b028953413ce9a3787f2d45e9e1459d0acbcc5e6499e7cb3470eb4bb83a79
Press [ENTER] once you've funded the address.
Account deployment transaction: 0x04348a81c550192ee75dad0183d432b0d18ac497dd8188d145979282fb649008
Waiting for transaction 0x04348a81c550192ee75dad0183d432b0d18ac497dd8188d145979282fb649008 to confirm. If this process is interrupted, you will need to run `starkli account fetch` to update the account file.
Transaction not confirmed yet...
Transaction not confirmed yet...
Transaction 0x04348a81c550192ee75dad0183d432b0d18ac497dd8188d145979282fb649008 confirmed
```

Okay @xJonathanLEI thanks! Thank you guys for your assistance.
