### ISSUE TITLE
question about mine-udc-salt

### ISSUE THREAD

**Issue by script-money** [xJonathanLEI/starkli#45]
I want to compute the salt that make a contract(calldata_len is 0) start with *0x04515*, I use `starkli lab mine-udc-salt --prefix 4515 --suffix 0 --deployer-address [DEPLOYER]   [CLASSHASH]` but show *Error: invalid bit: 5*

1. Could you give example how to do it?
2. Can `--suffix` be optional? 
3. At `https://github.com/xJonathanLEI/starkli/blob/e4d23076b67c05fccc2d7bda069561daaa1fde06/src/subcommands/lab/mine_udc_salt.rs#L110` , `let prefix_bits = self.suffix` should be `let prefix_bits = self.prefix`

**Comment by xJonathanLEI** [comment]
As a general tip, you should probably not use `--deploy-address` but instead use `--not-unique`, as `--not-unique` would allow you to deploy with any account using the mined hash.

The `--prefix` is in _bits_. `4515` is `0100010101000101` in hex. So the correct command would be:

```console
starkli lab mine-udc-salt --prefix "0100010101000101" --suffix "" --not-unique [CLASSHASH]
```

**Comment by xJonathanLEI** [comment]
Regarding point 3, the code is correct. The internal repr is reversed on purpose to be compared against the `to_bits_le` method on `FieldElement`.

**Comment by script-money** [comment]
> As a general tip, you should probably not use `--deploy-address` but instead use `--not-unique`, as `--not-unique` would allow you to deploy with any account using the mined hash.
> 
> The `--prefix` is in _bits_. `4515` is `0100010101000101` in hex. So the correct command would be:
> 
> ```
> starkli lab mine-udc-salt --prefix "0100010101000101" --suffix "" --not-unique [CLASSHASH]
> ```

Thank you for your response. I have successfully deployed a contract start with 0x04515. There was a small error, the hex you provided was 4545, not 4515.
