### ISSUE TITLE
Issue with Starkli Deployment and Class Hash Retrieval

### ISSUE THREAD

**Issue by Immanuelolivia1** [xJonathanLEI/starkli#50]
I encountered an issue while attempting to declare my first Cairo contract on Starknet using Starkli following the giudes from an article authored by [David Barreto](https://medium.com/@barretollano?source=post_page-----86ea914a2933--------------------------------). After successfully installing Starkli using the following command:
``` 
curl https://get.starkli.sh | sh 
```

 I used this command to declare:

```
starkli declare target/dev/cairo_intro_Balance_counter.sierra.json --account $STARKNET_ACCOUNT
```

I provided the required password (1234), but the process resulted in the following error:

```
Error: No such file or directory (os error 2)
```

This unexpected error prevented the successful deployment of my Cairo contract.

Additionally, when attempting to retrieve the class hash for Goerli using this command:
```
starkli block-number --network goerli-1
```
I encountered the following error:

```
data did not match any variant of enum GatewayResponse
```
but i can successfully get the class hash for mainnet using this command:
```
starkli block-number --network mainnet
```

It seems that this issue is related to Starkli functionality, and I would appreciate it if the maintainers could investigate and provide feedback on resolving these errors.

**Additional Information:**
- Operating System: macOS Big Sur version 11.7.10
- Starkli Version: 0.1.20 (e4d2307)

Your prompt attention to this matter and any assistance in resolving these issues would be highly appreciated.If you need more info I'll provide it as soon as possible. Thank you.

**Comment by glihm** [comment]
Hello @Immanuelolivia1!

Could you give it a try following the [101 in the Starkli book](https://book.starkli.rs/tutorials/starkli-101)?

Such kind of error as below are usually a local issue / configuration of your account path. Could you provide the `$STARKNET_ACCOUNT` content?

Also, don't hesitate to check in the book the section related to [environment variables](https://book.starkli.rs/tutorials/starkli-101#fund-and-deploy-the-account) that Starkli looks for. This may also help you configuring Starkli.

Finally, about the gateway, please consider that the gateway is not the preferred way to operate, as explained in the [provider](https://book.starkli.rs/providers) section of the book.

Don't hesitate to answer if more doubts persist. :+1:

**Comment by tonypony220** [comment]
@glihm but seems there are actually some issue? Because starkli sends BlockId params on Declare, but I don't see it in rpc
example with goerli: 
```
➜  starkli declare out.json
Enter keystore password:
Sierra compiler version not specified. Attempting to automatically decide version to use...
Network detected: goerli. Using the default compiler version for this network: 2.4.0. Use the --compiler-version flag to choose a different version.
Declaring Cairo 1 class: 0x02393b0c64950d0af308dc1b7cd2f09cfa6f4248d7db8715f3aa00452d832ba7
Compiling Sierra class to CASM with compiler version 2.4.0...
CASM class hash: 0x06008918921ac9f5d08d5263206ca294f17f799d995f8c875b1e4697b3cb0670
Error: JSON-RPC error: code=-32602, message="Invalid params"
```
