### ISSUE TITLE
How to deploy a contract on the 0.13.0 testnet?

### ISSUE THREAD

**Issue by script-money** [xJonathanLEI/starkli#52]
I want to declare new contract in new testnet, but show error below. How should I do next?
```
starkli declare target/dev/src_Test.contract_class.json
Enter keystore password:
Sierra compiler version not specified. Attempting to automatically decide version to use...
Unknown network. Falling back to the default compiler version 2.1.0. Use the --compiler-version flag to choose a different version.
Declaring Cairo 1 class: 0x06fe4be614eddfe1ca0c5ab160f132b4d690cea0d7e2e82a031d464db7b6c6db
Compiling Sierra class to CASM with compiler version 2.1.0...
Error: error from the program registry
```

RPC:
https://starknet-sepolia.public.blastapi.io/rpc/v0_6

Scarb version:
scarb 2.4.0 (cba988e68 2023-12-06)
cairo: 2.4.0 (https://crates.io/crates/cairo-lang-compiler/2.4.0)
sierra: 1.4.0

starkli --version
0.1.20 (e4d2307)

**Comment by glihm** [comment]
Hello! Thank you for the report. A PR has been merged to solve this issue https://github.com/xJonathanLEI/starkli/pull/51.
At the next release you'll be able to provide the new compiler version. 👍🏻
