### ISSUE TITLE
Feature request: Not able to deploy contract to starknet using scarb nightly and above 2.3.1

### ISSUE THREAD

**Issue by 10priyanshudhiman** [xJonathanLEI/starkli#62]
I am using these as my environment variable to deploy contract and respective versions
Scarb version :- 2.4.1+nightly-2024-01-06 (9583fdec4 2024-01-06)
cairo version :- cairo: 2.4.1 (adeb61730)

`export STARKNET_ACCOUNT=~/.starkli-wallets/deployer/infura.json 
export STARKNET_RPC=https://starknet-goerli.infura.io/v3/b7be8b0d609c4500b14a148fa5654c7d

export STARKNET_KEYSTORE=~/.starkli-wallets/deployer/testaccount1.json`

so when i am trying to fetch the account it works fines as 
`0x04b90b40d1928284523ad190fec328e8dcd07c68a9290a5f92e3859a99a27ec0 --output ~/.starkli-wallets/deployer/testaccount1.json 
Account contract type identified as: Braavos

Description: Braavos official proxy account (legacy)`

But when i am trying to declare the contract it shows me an error:-

`Enter keystore password: 

Error: serde-json: missing field `crypto` at line 22 column 1`

I tried for various others version although it works fine for scarb 2.3.1 and cairo 2.3.1 but not for above versions like 2.4.0

**Comment by xJonathanLEI** [comment]
Hi I know it's been a while but it looks like you're using the wrong file for keystore. This is probably not an issue of Starkli. Closing this optimistically. Feel free to reopen.
