### ISSUE TITLE
install v 1.20.0 starkli

### ISSUE THREAD

**Issue by Rezaheydariii** [xJonathanLEI/starkli#66]
How can I install a specific version on Linux?

**Comment by glihm** [comment]
> How can I install a specific version on Linux?

You should use starkliup: https://book.starkli.rs/installation.

With the command `starkliup --v 0.1.20`, you should have the correct version installed.

**Comment by xJonathanLEI** [comment]
Slight correction for anyone who stumbles across this in the future. It should be `-v` not `--v`. So it's:

```console
starkliup -v 0.1.20
```

But thank you @glihm for the prompt response!
