### ISSUE TITLE
Fetch account error

### ISSUE THREAD

**Issue by InvisEA** [xJonathanLEI/starkli#68]
I am trying to fetch account and get the following error:
![image](https://github.com/xJonathanLEI/starkli/assets/6782023/2bf5ed93-399f-4156-96df-b02907a475a4)

Do I understand correctly that Cairo v2 smart wallets are not supported yet?
My wallet:
https://goerli.voyager.online/contract/0x02ca27fbf157cd0550fb6bf980dd3e43868b75b106b242e50316c153de65e418

**Comment by xJonathanLEI** [comment]
Hi with the latest version of Starkli it should work now. Please run `starkliup`.
