### ISSUE TITLE
Support Braavos account class hash

### ISSUE THREAD

**Issue by parketh** [xJonathanLEI/starkli#69]
Add support for latest Braavos account class hash: `0x00816dd0297efc55dc1e7559020a3a825e81ef734b558f03c83325d4da7e6253`

Contract class from [here](https://github.com/myBraavos/braavos-account-cairo).

**Comment by xJonathanLEI** [comment]
Thanks for reporting. This is now supported in Starkli v0.2.6. Please run `starkliup` and it should work.
