### ISSUE TITLE
Feature request: calculate transaction hash of a raw transaction

### ISSUE THREAD

**Issue by odednaor** [xJonathanLEI/starkli#71]
It would be nice if starkli supported calculating the transaction hash of a raw transaction.

**Comment by xJonathanLEI** [comment]
What do you mean a raw transaction? Starkli currently doesn't expose any raw transaction format. What experience do you have in mind?

**Comment by odednaor** [comment]
Yeah, makes sense. Maybe Starkli is not the right place for this.
