### ISSUE TITLE
Error: unknown class hash

### ISSUE THREAD

**Issue by chiemezie1** [xJonathanLEI/starkli#72]
Trying to generate account.json, which contain open configuration file 
 with the command  
```
starkli account fetch <YOUR WALLET ADDRESS> --rpc https://starknet-testnet.public.blastapi.io/rpc/v0_6  --output account.json
```
Getting the error 

> 0x029927c8af6bccf3f6fda035981e765a7bdbf18a2dc0d630494f8758aa908e2b is not a known account class hash. If you believe this is a bug, submit a PR to:
>     https://github.com/xJonathanLEI/starkli
> Error: unknown class hash: 0x029927c8af6bccf3f6fda035981e765a7bdbf18a2dc0d630494f8758aa908e2b

**Meanwhile the wallect address is correct**

_Terminal screenshort_
![Screenshot 2024-02-23 074200](https://github.com/xJonathanLEI/starkli/assets/106808580/54c20db5-9f38-4821-94e6-f7cd7135d594)

**Comment by agungtri222** [comment]
up I got this error too

**Comment by xJonathanLEI** [comment]
This is because Argent updated the account contract. Support for it has actually been added in https://github.com/xJonathanLEI/starkli/commit/98a9009f18ade55297b5d3b6bae2aacb843b8819 but not released yet. I'm working on also adding the new Cairo 1 Braavos class hash support before making a release.

**Comment by xJonathanLEI** [comment]
That commit has now been released. Upgrade to the latest Starkli version and it should work.

Btw I see you're using the Blash public RPC. You can actually use the [free RPC vendor](https://book.starkli.rs/providers#free-rpc-vendors) feature like so:

```console
starkli account fetch 0x0484bb449013d98a0f1b900767a53ce6f4335dff8723d5ba0b3ea1f3e7e7c57a --network goerli --output stackie_account.json
```
