### ISSUE TITLE
Got 'Unknown ap change' error while moving

### ISSUE THREAD

**Issue by johnny24-dev** [xJonathanLEI/starkli#73]
I can't declare contract

Sierra compiler version not specified. Attempting to automatically decide version to use...
Network detected: goerli. Using the default compiler version for this network: 2.4.0. Use the --compiler-version flag to choose a different version.
Declaring Cairo 1 class: 0x02ae888dcb47377c1e8bf5a1353004a0ba9f22ba577c0c57258fb93fbe0b57bd
Compiling Sierra class to CASM with compiler version 2.4.0...
Error: #4402->#4403: Got 'Unknown ap change' error while moving [32].

using : strkli 0.2.5 , 
scarb 2.5.4 (28dee92c8 2024-02-14)
cairo: 2.5.4 (https://crates.io/crates/cairo-lang-compiler/2.5.4)
sierra: 1.4.0

**Comment by xJonathanLEI** [comment]
Have you tried adding `--compiler-version 2.5.3`?

**Comment by johnny24-dev** [comment]
> Have you tried adding `--compiler-version 2.5.3`?

yes, I tried but still error

**Comment by xJonathanLEI** [comment]
Would be helpful if you can provide the full Sierra class you're trying to declare.

**Comment by xJonathanLEI** [comment]
Issue staled. This is likely just a compiler version mismatch issue.
