### ISSUE TITLE
Can't regonize argent X class

### ISSUE THREAD

**Issue by UIZorrot** [xJonathanLEI/starkli#76]
When using starkli account fetch, it output:
0x029927c8af6bccf3f6fda035981e765a7bdbf18a2dc0d630494f8758aa908e2b is not a known account class hash
It's in fact the argent X account class

**Comment by zmalatrax** [comment]
Related to #82 
Adding a flag for custom class hashes when using `starkli account fetch`, bypassing the [`KNOWN_ACCOUNT_CLASSES`](https://github.com/xJonathanLEI/starkli/blob/f59724e10cdd069e4b6c0b18ad131f3c6a7f6cca/src/account.rs#L23) array would be a great workaround in between updating the array.

**Comment by swetshaw** [comment]
Hi, I am facing the same issue. Using ArgentX wallet in starkli fetch and getting the error `0x029927c8af6bccf3f6fda035981e765a7bdbf18a2dc0d630494f8758aa908e2b is not a known account class hash.`

Would be helpful if this could be resolved on priority

**Comment by swetshaw** [comment]
Same issue with Braavos Wallet. Opened issue here #84

**Comment by xJonathanLEI** [comment]
@swetshaw What Starkli version are you using? This class hash should be present on any version since v0.2.5.

**Comment by jorgezerpa** [comment]
Hi! the problem still remains, when I run 
'''
starkli account fetch 0x0416575467BBE3E3D1ABC92d175c71e06C7EA1FaB37120983A08b6a2B2D12794 --output ~/.starkli-wallets/deployer/account.json
'''

Got the error:
![image](https://github.com/user-attachments/assets/50212ece-b418-42c4-a5d0-a6b8eb80558c)


My starkli version is 0.3.2 (89690d4)

**Comment by pankaj829** [comment]
![Screenshot from 2024-11-19 11-00-26](https://github.com/user-attachments/assets/8077be7a-4f98-43c6-90d8-a7517741335b)
Same issue with version 0.3.5
