### ISSUE TITLE
Problem with .env in Fish shell

### ISSUE THREAD

**Issue by Vid201** [xJonathanLEI/starkli#80]
The .env file that is generated on the fly is same for all shells - but the syntax for env file doesn't work in Fish shell.

Each time the Fish terminal is open, the error appears.

`~/.starkli/env (line 4): 'case' builtin not inside of switch block
case ":\${PATH}:" in
^
from sourcing file ~/.starkli/env
	called on line 12 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup
.: Error while reading file “/home/vid/.starkli/env”`

https://github.com/xJonathanLEI/starkli/blob/master/starkliup/install

**Comment by iamashwin99** [comment]
I have the same problem

**Comment by xJonathanLEI** [comment]
Hmm interesting didn't know Fish uses a different syntax. Taking a look now.

**Comment by xJonathanLEI** [comment]
I just also realized that we haven't supported Fish auto completion the entire time except on Termux for Android... will fix that too.

**Comment by xJonathanLEI** [comment]
Just pushed bb2bc2ca074056f2faccd2d4b7dc2360705b1084 which should have fixed this. Tested with my FIsh shell installation and it works, both the adding `PATH` part and auto completion. I'm not a regular Fish user though, so I could be missing something.

Optimistically closing this as completed. Please feel free to re-open as needed.
