### ISSUE TITLE
unknown class hash

### ISSUE THREAD

**Issue by A-coolcreator** [xJonathanLEI/starkli#86]
even after transferring ETH from my wallet starknet wallet to another starknet wallet, terminal reads unknown class hash.

image for reference :
![image](https://github.com/xJonathanLEI/starkli/assets/70680928/936297f4-20f0-41c1-8cc5-9af73ca5fdfd)

@xJonathanLEI  please help in figuring out this problem's solution.

**Comment by xJonathanLEI** [comment]
What Starkli version are you using? If you're using v0.2.6 or newer you shouldn't see this error.
