### ISSUE TITLE
Unable to detect platform. Please install starkli from source.

### ISSUE THREAD

**Issue by JY20** [xJonathanLEI/starkli#87]
Hi when trying to run starkliup to install starkli. I had gotten the error of Unable to detect platform. Please install starkli from source.
Is there another way to install starkliup?

**Comment by xJonathanLEI** [comment]
Hi thanks for reporting. What's your operating system and processor architecture?

**Comment by JY20** [comment]
Hi, I'm currently trying to setup on windows 64bit

**Comment by xJonathanLEI** [comment]
Unfortunately, `starkliup` currently only supports Linux/macOS. You could use `starkliup` on Windows via WSL, but for _native_ Windows usage, you'll have to either install from source, manually download the executable from GitHub releases. See [this Starkli book page](https://book.starkli.rs/installation) for details.
