### ISSUE TITLE
Env file break my gnome UI session

### ISSUE THREAD

**Issue by FilipLaurentiu** [xJonathanLEI/starkli#88]
This was a weird problem and difficult to track.
I made a post on StackExchange with my problem, initially unrelated to this tool, and someone find the problem to be the env file from starkli. [Post](https://unix.stackexchange.com/a/777869/319079)
You can find more details there.

**Comment by xJonathanLEI** [comment]
This is weird. I've used Starkli both on Gnome and KDE and never saw an issue.

But yes removing `.starkli` pretty much does everything, except now you'll be left with a message from your shell saying it can't load the env file. You'd have to remove the line loading that file as well.

**Comment by xJonathanLEI** [comment]
OK I checked the stackexchange link and it looks like it's that the `env` file does not work with `dash`. Lemme try to work on a fix.

**Comment by xJonathanLEI** [comment]
Alright now I see why it works on say Bash. I always assumed that as long as the shabang says to use `/bin/sh` Bash would automatically use POSIX mode, which is somewhat true: if you directly execute the script in Bash with something like `./env`, it uses POSIX mode and fails. I've been relying on this behaviour to capture non compliance with POSIX.

But as it turns out, running the script with `. <path_to_script>` does not use POSIX mode, so Bash has been doing alright sourcing from the non-POSIX-compliant `env` file.

So essentially, I always knew that my scripts need to be POSIX compliant, but I thought relying on the shebang of `/bin/sh` serves as a test on that as Bash would run in POSIX mode. Turns out it's not true. Now I just need to _actually_ make sure the script is POSIX compliant and it shall fix this.

**Comment by FilipLaurentiu** [comment]
> That said, it's pretty wild that an error _at the end of_ a _shell config script_ can cause the UI to fail to load...

I was also very surprised to see that my UI failed from such a small problem.
This is somehow similar with the recent situation with CrowdStrike :laughing: 

Thank you for taking a look :+1:

**Comment by xJonathanLEI** [comment]
I just pushed the fix. If you would, could you please help test the fix by installing it again? So just run:

```console
curl https://get.starkli.sh | sh
```

and of course then run `starkliup` as instructed.

The issue should be gone now.

**Comment by FilipLaurentiu** [comment]
> I just pushed the fix. If you would, could you please help test the fix by installing it again? So just run:
> 
> ```
> curl https://get.starkli.sh | sh
> ```
> 
> and of course then run `starkliup` as instructed.
> 
> The issue should be gone now.

I just run the instructions and restart the pc, unfortunately I had the same error as before, my UI didn't load, but now I know what to do.

The version that I have it installed now is 
```
starkli --version
0.3.3 (1a028fb)
```
which is the old one. So I assume you need to do another release with the fix

**Comment by xJonathanLEI** [comment]
Thanks for helping with the test!

That's very strange. Could you please post the content of your `/home/filip/.starkli/env` file?

As for a new release, nope that's not necessary, as the `install` script is what's causing the issue, but that one gets updated immediately on each commit, without relying on releases.

**Comment by FilipLaurentiu** [comment]
> Thanks for helping with the test!
> 
> That's very strange. Could you please post the content of your `/home/filip/.starkli/env` file?
> 
> As for a new release, nope that's not necessary, as the `install` script is what's causing the issue, but that one gets updated immediately on each commit, without relying on releases.

The error from the logs seems to be different
> Jul 30 17:09:02 filip-thinkstation /usr/libexec/gdm-x-session[3336]: /etc/gdm3/Xsession: Beginning session setup...
> Jul 30 17:09:02 filip-thinkstation /usr/libexec/gdm-x-session[3336]: /etc/gdm3/Xsession: 1: eval: Syntax error: "(" unexpected

the `/home/filip/.starkli/env` file
> 
> #!/bin/sh
> 
> # Adds binary directory to PATH
> case ":${PATH}:" in
>   *:/home/filip/.starkli/bin:*)
>     ;;
>   *)
>     export PATH="/home/filip/.starkli/bin:$PATH"
>     ;;
> esac
> 
> # Loads completions based on shell
> if [ -n "$ZSH_NAME" ]; then
>     eval "fpath=(/home/filip/.starkli/share/zsh-completions $fpath)"
>     autoload -U compinit
>     compinit
> else
>     case $SHELL in
>         */bash)
>             if [ -f "/home/filip/.starkli/share/bash-completions/starkli" ]; then
>                 . /home/filip/.starkli/share/bash-completions/starkli
>             fi
>             ;;
>         */zsh)
>             eval "fpath=(/home/filip/.starkli/share/zsh-completions $fpath)"
>             autoload -U compinit
>             compinit
>             ;;
>     esac
> fi
>

**Comment by FilipLaurentiu** [comment]
> > Thanks for helping with the test!
> > That's very strange. Could you please post the content of your `/home/filip/.starkli/env` file?
> > As for a new release, nope that's not necessary, as the `install` script is what's causing the issue, but that one gets updated immediately on each commit, without relying on releases.
> 
> The error from the logs seems to be different
> 
> > Jul 30 17:09:02 filip-thinkstation /usr/libexec/gdm-x-session[3336]: /etc/gdm3/Xsession: Beginning session setup...
> > Jul 30 17:09:02 filip-thinkstation /usr/libexec/gdm-x-session[3336]: /etc/gdm3/Xsession: 1: eval: Syntax error: "(" unexpected
> 
> the `/home/filip/.starkli/env` file
> 
> ```
> #!/bin/sh
> 
> # Adds binary directory to PATH
> case ":${PATH}:" in
>   *:/home/filip/.starkli/bin:*)
>     ;;
>   *)
>     export PATH="/home/filip/.starkli/bin:$PATH"
>     ;;
> esac
> 
> # Loads completions based on shell
> if [ -n "$ZSH_NAME" ]; then
>     eval "fpath=(/home/filip/.starkli/share/zsh-completions $fpath)"
>     autoload -U compinit
>     compinit
> else
>     case $SHELL in
>         */bash)
>             if [ -f "/home/filip/.starkli/share/bash-completions/starkli" ]; then
>                 . /home/filip/.starkli/share/bash-completions/starkli
>             fi
>             ;;
>         */zsh)
>             eval "fpath=(/home/filip/.starkli/share/zsh-completions $fpath)"
>             autoload -U compinit
>             compinit
>             ;;
>     esac
> fi
> ```

> Jun 06 16:19:57 filip-thinkstation /usr/libexec/gdm-x-session[3156]: /etc/gdm3/Xsession: Beginning session setup...
> Jun 06 16:19:57 filip-thinkstation /usr/libexec/gdm-x-session[3156]: /etc/gdm3/Xsession: 14: /home/filip/.starkli/env: Syntax error: "(" unexpected (expecting "fi")

This was the first error, it mention the name of the tool. Now the tool is not mentioned. Good luck finding the problem now :laughing:

**Comment by FilipLaurentiu** [comment]
> My fix was simply to hide the non-POSIX-compliant part that uses an array behind an `eval`, so now the whole script itself becomes POSIX-compliant, as any non-compliant part is now just a string.
> 
> So everything should be fine _as long as_ a POSIX shell does not end up `eval`-ing the now stringified command.
> 
> I'm suspecting that it does in your case. So somehow the script is convinced that the script executing it is a `zsh`, and falls into the `eval` lines anyway.

maybe the instruction is wrong ?

I have a few `eval` instructions in my `.zshrc` file and they work fine
```

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

**Comment by xJonathanLEI** [comment]
`eval` is fine. It's what's in `eval` that's problematic. That's not POSIX and rightfully not so: it's supposed to be executed by `zsh`, not a non-POSIX shell.

It would be extremely helpful if you can help test it further. You can do so by running the installation process again, but this time, before restarting, replace the content in the problematic `env` file with:

```
#!/bin/sh

echo "Execution starts" >> /home/filip/starkli.log

# Adds binary directory to PATH
case ":${PATH}:" in
  *:/home/filip/.starkli/bin:*)
    ;;
  *)
    export PATH="/home/filip/.starkli/bin:$PATH"
    ;;
esac

echo "ZSH_NAME = $ZSH_NAME" >> /home/filip/starkli.log
echo "SHELL = $SHELL" >> /home/filip/starkli.log

# Loads completions based on shell
if [ -n "$ZSH_NAME" ]; then
    eval "fpath=(/home/filip/.starkli/share/zsh-completions $fpath)"
    autoload -U compinit
    compinit
else
    case $SHELL in
        */bash)
            if [ -f "/home/filip/.starkli/share/bash-completions/starkli" ]; then
                . /home/filip/.starkli/share/bash-completions/starkli
            fi
            ;;
        */zsh)
            eval "fpath=(/home/filip/.starkli/share/zsh-completions $fpath)"
            autoload -U compinit
            compinit
            ;;
    esac
fi

echo "Execution ends" >> /home/filip/starkli.log
```

Then, when you restart, it should still fail, but now there should be execution traces written to `/home/filip/starkli.log` which you can retrieve and post once UI works again.

**Comment by FilipLaurentiu** [comment]
> `eval` is fine. It's what's in `eval` that's problematic. That's not POSIX and rightfully not so: it's supposed to be executed by `zsh`, not a non-POSIX shell.
> 
> It would be extremely helpful if you can help test it further. You can do so by running the installation process again, but this time, before restarting, replace the content in the problematic `env` file with:
> 
> ```
> #!/bin/sh
> 
> echo "Execution starts" >> /home/filip/starkli.log
> 
> # Adds binary directory to PATH
> case ":${PATH}:" in
>   *:/home/filip/.starkli/bin:*)
>     ;;
>   *)
>     export PATH="/home/filip/.starkli/bin:$PATH"
>     ;;
> esac
> 
> echo "ZSH_NAME = $ZSH_NAME" >> /home/filip/starkli.log
> echo "SHELL = $SHELL" >> /home/filip/starkli.log
> 
> # Loads completions based on shell
> if [ -n "$ZSH_NAME" ]; then
>     eval "fpath=(/home/filip/.starkli/share/zsh-completions $fpath)"
>     autoload -U compinit
>     compinit
> else
>     case $SHELL in
>         */bash)
>             if [ -f "/home/filip/.starkli/share/bash-completions/starkli" ]; then
>                 . /home/filip/.starkli/share/bash-completions/starkli
>             fi
>             ;;
>         */zsh)
>             eval "fpath=(/home/filip/.starkli/share/zsh-completions $fpath)"
>             autoload -U compinit
>             compinit
>             ;;
>     esac
> fi
> 
> echo "Execution ends" >> /home/filip/starkli.log
> ```
> 
> Then, when you restart, it should still fail, but now there should be execution traces written to `/home/filip/starkli.log` which you can retrieve and post once UI works again.

`starkli.log` 


> Execution starts
> ZSH_NAME = 
> SHELL = /usr/bin/zsh
> Execution starts
> ZSH_NAME = zsh
> SHELL = /usr/bin/zsh
> Execution ends
> Execution starts
> ZSH_NAME = zsh
> SHELL = /usr/bin/zsh
> Execution ends

**Comment by xJonathanLEI** [comment]
Hmm interesting. So you can see here the first execution is the failure case:

```
Execution starts
ZSH_NAME =
SHELL = /usr/bin/zsh
```

it doesn't come with an _Execution ends_ because it failed on the `eval` line.

Unlike the subsequent 2 invocations, this first one is suspicious as it sets `SHELL` but not `ZSH_NAME`. It's not a true `zsh`.

It looks like that relying on `SHELL` to detect `zsh` is extremely unreliable. The most reliable way seems to be just using `ZSH_NAME`.

**Comment by FilipLaurentiu** [comment]
I run the install instructions again and restart, everything seems to be fine, shell autocompletion also work :clap: 

This error was from a bad configuration on my machine ?
I use zsh for my shell but I install it from https://ohmyz.sh/ which actually is an extension of the zsh

**Comment by FilipLaurentiu** [comment]
> Thanks for testing and great that it works!
> 
> > This error was from a bad configuration on my machine ?
> 
> Honestly, this isn't _exactly_ a bug on your system. Like... `zsh` technically [does not set `SHELL`](https://linux.die.net/man/1/zshparam), but some systems (like yours) do set it, which is not wrong.
> 
> Then, your system _happens to_ decide to load the script with a POSIX shell like `dash`, or maybe it's a non-POSIX shell running in POSIX mode, which _happens to_ not set `SHELL`, leaving it pointing to `zsh`. Since this shell that's now responsible for loading `env` is POSIX, and the `eval` statement runs something non-POSIX, thinking the shell is `zsh`, the thing happened and your system failed.
> 
> I have never seen this issue reported before so I guess it's gotta be a bit rare. Thanks to your report the issue in my `zsh` detection code was uncovered and now fixed :)
> 
> Closing this as completed.

Thank you for your time :clap: You seem to be a Linux guru :+1: I learned some new things today :smile: 
And thank you for creating this tool, is very cool
