### ISSUE TITLE
Unable to declare classes fetched by `starkli class-by-hash`

### ISSUE THREAD

**Issue by amanusk** [xJonathanLEI/starkli#90]
It should be possible to declare the results fetched by `starkli class-by-hash` or `class-at` to another chain (e.g. devnet/katana) without formatting the resulting file

Steps to reproduce:
Fetching a class from sepolia:

```
starkli class-by-hash 0x00816dd0297efc55dc1e7559020a3a825e81ef734b558f03c83325d4da7e6253 > braavos.json
```

Trying to declare on another chain:
```
starkli declare ./braavos.json
Enter keystore password:
Error: failed to parse contract artifact
```

**Comment by amanusk** [comment]
Closing, works with `starkli class-by-hash 0x00816dd0297efc55dc1e7559020a3a825e81ef734b558f03c83325d4da7e6253 --parse`

Perhaps this can stated in docs/help that flag is needed for declaration

**Comment by xJonathanLEI** [comment]
Just added a section for this: https://book.starkli.rs/declaring-classes#redeclaring-classes
