### ISSUE TITLE
Allow using custom account class hashes

### ISSUE THREAD

**Issue by amanusk** [xJonathanLEI/starkli#94]
# Descrbie the Problem
When creating a new account, `starkli` lets you select one of Argent, Braavos or OZ accounts. It uses the latest hash available from these accounts, and what was updated in the [known accounts list](https://github.com/xJonathanLEI/starkli/blob/bb2bc2ca074056f2faccd2d4b7dc2360705b1084/src/account.rs#L23)
Sometimes the lastest account class is not yet declared on every network, or there is a need to use a custom class hash, with similar ABI but changed functionality. 
It would be useful for `starkli` to allow to specify a custom account class hash upon creation. 

## Proposed interface
starkli account oz init --custom_class_hash <0x...>

This will assume the user knows what they are doing by specifying a specific account class hash when creating their account. (Potentially, it is also possible to check if the class has the same ABI, but that is extra)

**Comment by xJonathanLEI** [comment]
Implemented in 0e9b70658fa60453914fd08d56490166f0f09ba7. Note that specifying account variant when fetching is not supported yet.
