### ISSUE TITLE
"(Input too long for arguments)" error when executing a transaction with starkli testnet sepolia

### ISSUE THREAD

**Issue by johnny24-dev** [xJonathanLEI/starkli#95]
![Screenshot 2024-08-07 at 13 58 54](https://github.com/user-attachments/assets/56a3adb2-5d97-4f15-938e-1b5f1c9fa6fe)

**Comment by johnny24-dev** [comment]
starkli deploy 0x013267b9ab398ff17b9260d91fb21e8167bb6bf4aca757152eec723237858dff --network=sepolia                                                     
Enter keystore password: 
Deploying class 0x013267b9ab398ff17b9260d91fb21e8167bb6bf4aca757152eec723237858dff with salt 0x031348bfe86fb25cf43e3937ad09c5db07a8a8f7a9b0fad670f50fb11a7962ed...
The contract will be deployed at address 0x0531f90b083d4011a22154a60366f8f8051ad83696cfe7a077087383009e1bfd
Error: TransactionExecutionError (tx index 0): failed txn 3320030355660199624590554122105147476480074255987206367901440199211263327183 reason: Transaction validation has failed:
0: Error in the called contract (contract address: 0x01c25342f2158a2c18ebc8f3b3e38b487527828c39d99e7caed07c407131e986, class hash: 0x036078334509b514626504edc9fb252328d1a240e4e948bef8d0c08dff45927f, selector: 0x0162da33a4585851fe8d3af3c2a9c60b557814e221e0d4f30ff0b2189d9c7775):
Execution failed. Failure reason: 0x496e70757420746f6f206c6f6e6720666f7220617267756d656e7473 ('Input too long for arguments').
 Execution failed. Failure reason: 0x496e70757420746f6f206c6f6e6720666f7220617267756d656e7473 ('Input too long for arguments').

**Comment by xJonathanLEI** [comment]
This is most likely due to using an account file that was previously generated, but with the account itself having been upgraded to Cairo 1 already. Try deleting your account file and generating it again using `starkli account fetch`.
