### ISSUE TITLE
Starkli does not yet support Cairo 2.7.0 and Sierra 1.6.0

### ISSUE THREAD

**Issue by amanusk** [xJonathanLEI/starkli#96]
Cannot declare 2.7.0 and sierra 1.6.0 contracts with starkli.
Please add :) 

Optionally, add support for universal-sierra-compiler which is usually up-to-date

**Comment by piotmag769** [comment]
@amanusk [USC](https://github.com/software-mansion/universal-sierra-compiler) already supports latest sierra 😄

**Comment by xJonathanLEI** [comment]
Added in e2210b13ada5d14583d20bd0732719d5bf477976. Now defaults to 2.7.0 on sepolia and 2.6.4 on mainnet.
