### ISSUE TITLE
Sierra Compiler Version Compatibility Issue During Contract Declaration

### ISSUE THREAD

**Issue by caseywescott** [xJonathanLEI/starkli#97]
**Expected Behavior:**
The contract should be declared successfully without any compiler version mismatch issues.

**Actual Behavior:**
The command fails due to the inability to compile Sierra version 1.6.0 with the currently available compiler version (1.5.0).

using the hello_cairo example: 
starkli declare /Users/mymachine/hello_cairo/target/dev/hello_cairo_HelloStarknet.contract_class.json

Environment:

starkli version: 0.3.3 (1a028fb)
Sierra compiler version: 1.5.0
Contract Sierra version: 1.6.0
Network: Sepolia

**Comment by xJonathanLEI** [comment]
The current latest version of Starkli is able to handle Sierra 1.6.0. Closing.
