### ISSUE TITLE
Deploy account failed

### ISSUE THREAD

**Issue by huihzhao** [xJonathanLEI/starkli#98]
$ starkli account deploy /home/jimmy/.starkli-wallets/deployer/account.json --keystore ~/.starkli-wallets/deployer/keystore.json
WARNING: you're using neither --rpc (STARKNET_RPC) nor --network (STARKNET_NETWORK). The `sepolia` network is used by default. See https://book.starkli.rs/providers for more details.
Enter keystore password: 
Error: TransactionExecutionError (tx index 0): failed txn 2180479412427928049155873737291408786753881290901682334008209371405073530908 reason: Contract constructor execution has failed:
0: Error in the contract class constructor (contract address: 0x072f7e2b9caf7a475e237110843710af48aa3f05bc53ff440347b127fa3c9f07, class hash: 0x036078334509b514626504edc9fb252328d1a240e4e948bef8d0c08dff45927f, selector: 0x028ffe4ff0f226a9107253e17a904099aa4f63a02a5621de0576e5aa71bc5194):
Execution failed. Failure reason: 0x4661696c656420746f20646573657269616c697a6520706172616d202331 ('Failed to deserialize param #1').
 Error in the contract class 1527385455757960447222183650373907436110918566631056279654792814069834683007 constructor (selector: Some(EntryPointSelector(0x28ffe4ff0f226a9107253e17a904099aa4f63a02a5621de0576e5aa71bc5194)), address: ContractAddress(PatriciaKey(0x72f7e2b9caf7a475e237110843710af48aa3f05bc53ff440347b127fa3c9f07))): Execution failed. Failure reason: 0x4661696c656420746f20646573657269616c697a6520706172616d202331 ('Failed to deserialize param #1').

**Comment by xJonathanLEI** [comment]
Looks like an [Argent account contract v0.4.0](https://github.com/argentlabs/argent-contracts-starknet/releases/tag/update-2024Q2) which contains a breaking change on the constructor signature. This has been fixed in 5b4f853908b4ffb7cb019d55a6f08d67ece35962 and will be released in about an hour.
